const mongoose = require('mongoose');
require('dotenv').config();
const User = require('./models/User');
const { initCounters } = require('./models/Counter');

const createAdminUser = async () => {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');
        
        // Initialize counters
        await initCounters();
        
        // Delete existing admin if exists
        const deleted = await User.deleteOne({ username: 'admin' });
        if (deleted.deletedCount > 0) {
            console.log('Removed existing admin user');
        }
        
        // Create new admin user (ID will be auto-generated by pre-save hook)
        const admin = new User({
            username: 'admin',
            password: 'admin123',
            role: 'admin'
        });
        
        await admin.save();
        console.log('\n✅ Admin user created successfully!');
        console.log('📝 Username: admin');
        console.log('🔑 Password: admin123');
        console.log(`🆔 User ID: ${admin.user_id}`);
        
        // Verify user was created
        const userCheck = await User.findOne({ username: 'admin' }).select('-password');
        if (userCheck) {
            console.log('\n✅ Verification: Admin user exists in database');
            console.log('User details:', {
                username: userCheck.username,
                user_id: userCheck.user_id,
                role: userCheck.role,
                created_at: userCheck.createdAt
            });
        } else {
            console.log('\n❌ Verification failed: Admin user not found');
        }
        
        await mongoose.disconnect();
        console.log('\nDisconnected from MongoDB');
        
    } catch (error) {
        console.error('Error creating admin user:', error);
        if (error.code === 11000) {
            console.error('Duplicate key error. Please check if user already exists.');
        }
        process.exit(1);
    }
};

// Run the function
createAdminUser();